spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/postgres_demo
    # username: postgres
    # password: root
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
      # dialect: org.hibernate.dialect.PostgreSQLDialect
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect